### ISSUE TITLE
little better code effiency

### ISSUE THREAD

**Issue by kdschlosser** [MathyV/lvgl_esp32_mpy#1]
in the clear function you have the following code.

```
uint16_t *buf = heap_caps_malloc(buf_size * sizeof(uint16_t), MALLOC_CAP_DMA);
assert(buf);

for (int i = 0; i < buf_size; i++)
{
    buf[i] = 0;
}
```

This would be more efficient code.

```
uint16_t *buf = heap_caps_calloc(1, buf_size * sizeof(uint16_t), MALLOC_CAP_DMA);
assert(buf);
```

calloc create and then clears the memory for you. 

I would also recommend using `heap_caps_free` to free the buffer as there is no gurantee of the stdlib having `free` redirected to `heap_caps_free`.

The other thing is you should probably not use DMA memory when clearing the display. This is because of the original ESP32 only having a very small amount of available DMA memory and the potential for their to be none available... With the clear function being called it is probably also better if it is a blocking call anyhow. 

The other issue I see is that you are working under the assumption that every display connected is always going to be an rgb565 display. This may not be the most ideal thing to do.

**Comment by MathyV** [comment]
Hi Kevin,

> This would be more efficient code.

You're correct, I actually wanted to change that, it just slipped my mind.

> I would also recommend using `heap_caps_free` to free the buffer as there is no gurantee of the stdlib having `free` redirected to `heap_caps_free`.

Actually, from the IDF manual:

>In IDF, free(p) is equivalent to heap_caps_free(p).

Since I'm only targetting ESP32, it doesn't really matter, but it provides a more uniform look so I'm changing it.
 
> The other thing is you should probably not use DMA memory when clearing the display. This is because of the original ESP32 only having a very small amount of available DMA memory and the potential for their to be none available... With the clear function being called it is probably also better if it is a blocking call anyhow.

I know, that is why I only use a 1 line buffer and clear line by line, first I used a full buffer and it actually didn't fit ;-) Since the purpose of this function is only to clear the screen at startup I don't mind the additional delay of this approach.

Anyway, for LVGL I'm using 2 * 20 line DMA buffers later on in the code so that'll bite me first if I come across a device where it doesn't fit in the future.

> The other issue I see is that you are working under the assumption that every display connected is always going to be an rgb565 display. This may not be the most ideal thing to do.

Every display I have available to me *right now* is an rgb565 display. As explained in the README.md I'll only add stuff I can actually test. Pull requests are welcome though if someone else has other hardware they can test it on, I'll gladly consider them.

Besides that, the lv_conf.h (which I copied from lv_binding_micropython) also has `LV_COLOR_DEPTH` set to 16, so there's more stuff to do if I ever want to support other displays.

Thanks for the feedback!

**Comment by kdschlosser** [comment]
I understand. The clear works without any issues? I have not looked at the code with regard to the DMA transfers and the SPI LCD interface. I don't know if it will keep on stacking the jobs or not or if each call to transmit the buffer stalls until the last transfer has finished. I believe it is going to stall because of having to set the memory address as to where to write the buffer data to. If that is what it does then you should be fine as it is not going to let the next write occur until the last one has finished.

The only thing I am thinking that might pose an issue if if you free the buffer before it has finished transmitting the last line. But I don't know if that would even be an issue unless that memory ends up getting used for something else before the transfer finishes. That could be an issue.

**Comment by MathyV** [comment]
As far as I could tell (I didn't check in the code) `esp_lcd_panel_draw_bitmap` only returns when the data is on the bus. I use the `on_color_trans_done` callback to notify LVGL that the data is flushed but in my earlier code I had `lv_disp_flush_ready` right after the `esp_lcd_panel_draw_bitmap` and it worked just the same.
